name = "ignite-pdf-worker"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for the worker
[env.production.vars]
ENVIRONMENT = "production"
CLIENT_URL = "https://your-client-domain.com"
ADMIN_URL = "https://your-admin-domain.com"

[env.development.vars]
ENVIRONMENT = "development"
CLIENT_URL = "http://localhost:3000"
ADMIN_URL = "http://localhost:3001"

# R2 bucket binding
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ignite-pdfs"

[[env.development.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ignite-pdfs-dev"

# Default environment (development)
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ignite-pdfs-dev"

[vars]
ENVIRONMENT = "development"
CLIENT_URL = "http://localhost:3000"
ADMIN_URL = "http://localhost:3001"
